server:
  port: 8010
  context-path: /v1

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: POST-SERVICE